In [1]:
import pandas as pd

df_final_web=pd.read_parquet(f'../data/processed/df_final_web.parquet')

In [2]:
print(df_final_web.info(memory_usage='deep'))

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9649 entries, 0 to 9648
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   uuid                 9649 non-null   object
 1   age                  9649 non-null   int64
 2   gender               9649 non-null   category
 3   dem_has_children     9649 non-null   category
 4   age_group            9649 non-null   category
 5   country_code         9649 non-null   category
 6   rural                9649 non-null   category
 7   dem_education_level  8986 non-null   object
 8   dem_full_time_job    9649 non-null   category
 9   normalized_job_code  5702 non-null   object
 10  awareness            9649 non-null   category
 11  vote                 9649 non-null   category
 12  effect               9649 non-null   category
 13  argumentsfor         9649 non-null   object
 14  argumentsagainst     9649 non-null   object
 15  Country              9649 non-null   object
dtypes: category(9), int64(1), object(6)
memory usage: 5.5 MB
None

In [3]:
df_final_web.nunique()

uuid                   9649
age                      52
gender                    2
dem_has_children          2
age_group                 3
country_code             28
rural                     2
dem_education_level       4
dem_full_time_job         2
normalized_job_code     156
awareness                 4
vote                      5
effect                    9
argumentsfor            674
argumentsagainst        881
Country                  28
dtype: int64

In [4]:
list_unique_jobs=df_final_web['normalized_job_code'].unique().tolist()

In [5]:
import requests

list_uuid=[]
list_title=[]

for x in list_unique_jobs:
    url=f'http://api.dataatwork.org/v1/jobs/{x}'
    response = requests.get(url).json()
    if list(response.keys())[0]=='error':
        pass
    else:
        list_uuid.append(response['uuid'])
        list_title.append(response['title'])

dict_uuid_title=dict(zip(list_uuid,list_title))
len(dict_uuid_title)

156

In [6]:
dict_uuid_title

{'861a9b9151e11362eb3c77ca914172d0': 'Automatic Data Processing Planner',
 '049a3f3a2b5f85cb2971ba77ad66e10c': 'Data Coordinator',
 'f4b2fb1aa40f661488e2782b6d57ad2f': 'Database Developer',
 '27af8700f5577cec835acee2cb90a2ff': 'Data Entry Specialist',
 'c1b670eba9ccb65e7c99f7da116d5b9c': 'Database Architect',
 'd71c4164c99a5f9bca773e755a72f40f': 'Geographic Information Systems Database Administrator (GIS Database Administrator)',
 '2ee80cf30e2483dfe0947adc0428f8c5': 'Crime Data Specialist',
 '897ef18a9321616495831a4b4b0c1bb2': 'Data Communications Software Consultant',
 'a003702c0cea282e17967772dd83de5e': 'Data Security Analyst',
 '04c82eae29e1c4a30eac0710b74ab276': 'Database Marketing Analyst',
 'fcaf4aac737e53ad24b9f32f08b8740f': 'Computer or Data Processing Systems Consultant',
 '3833bd699e7afe4665b595f282da0387': 'Database Development and Administration Project Manager',
 '19e384e977796c25780d8c28b12089c4': 'Naval Tactical Data System--Combat Information Center Watch Officer, General',
 '474b962c13632a04e42a546be4f11dbb': 'Data Coder Operator',
 'dac2e921c1f887d9efc4c06fa33c1397': 'Automatic Data Processing Customer Liaison (ADP Customer Liaison)',
 '996da29c84f5eed00da40c230f4c4078': 'Data Entry Representative',
 'cc2b26cc436bea36bda3bdd7367c411a': 'Data Processing Auditor',
 '25fe195cbf915c0824fa6c44e6d0008c': 'Maintenance Data Analyst',
 '76385cb24e831b3364279b9de5641d8f': 'Automatic Data Processing Systems Security Specialist (ADP Systems Security)',
 '16b67d7f57698455aefbc1ae1b358b50': 'Database Engineer',
 'b24ece3300d2f8ab34f9553e531183d6': 'Data Processing Systems Project Planner',
 '5db2c8d6539f983e1ca3d7c5b939e190': 'Database Administration Associate',
 '36675c937946c8a4fc5de7d0b4c850de': 'Data Warehousing Engineer',
 '847165cfda6b1dc82ae22b967da8af2f': 'Data Warehouse Developer',
 '2ca138b991c50dc6696238e5ad800142': 'Database Software Technician',
 '775190277a849cba701b306a7b374c0a': 'Data Officer',
 '022d0e3a40aa3e29bca6851542b27842': 'Data Keyer',
 '375017ea3a1a97f5ea676def873bb25b': 'Geographic Information Systems Data Specialist (GIS Data Specialist)',
 '1dd2fdc8a3981f2a1d8f0ca173952bb8': 'Database Administration Manager',
 'e605336f5a43949cb6b18054fd1937f1': 'Database Security Expert',
 '800b621aab5dac18f4caef621fa43a49': 'Data Systems Manager',
 'd06dfb43c95b585a89ae556c9221b573': 'Data Warehousing Manager',
 'a12a16280e22220f9354333f6fe1b22a': 'Geographic Information Systems Data Administrator (GIS Data Administrator)',
 '477b53ef09d37f098d5ed74f47fcbaec': 'Data Base Design Analyst',
 'e2f68bf748aea2c7d2254550c0c92b23': 'Director of Data Operations',
 '45033f83b6e0309eca9bcd76917f15d0': 'Database Modeler',
 '141ddda0f613da65a280521247de0e9f': 'Data Administrator',
 '3ddea1b52e520996e4ec9fb70dc8b86b': 'Field Artillery Automated Tactical Data System Specialist',
 '6408c0d7c7faa4ced47fbc8474698126': 'Database Design Analyst',
 '07b7555fa790debaf5b04d1409ad5f11': 'Database Security Administrator',
 'a4d5b8b38f9513825d0d94a981ebe962': 'Database Manager',
 '5e93fd1a58c8a67b295f69d87d1a940d': 'Geographic Information Systems Data Manager (GIS Data Manager)',
 '122f24bc911a79c26ca66210557dda07': 'Clinical Data Specialist',
 '76b0ba6af40991629e20dff36edd02a5': 'Data Management Information Technology Specialist',
 '970eb38c7b3eb080466052ea994af189': 'Internet Database Specialist',
 'cf2d4db3c258faa2499bdeeeed6721a5': 'GPS Field Data Collector (Global Positioning System Field Data Collector)',
 '90c5430dbc810aec8695af2f1f4c42e8': 'Electronic Data Processing Auditor (EDP Auditor)',
 '7bb15eefb19ed09c59349baad7e8469e': 'Database Coordinator',
 'ec3d88b2fd083b870b8c5a603898ed39': 'Databases Computer Consultant',
 '1f8576bdffa64f492405d02b842c41a6': 'Data Management Associate',
 'edc64316da9707432443c7a4461abe6c': 'Data Security Administrator',
 '6cf4d336112984368f83181ac5ffe948': 'Health Data Analyst',
 'd4624ed8068d24948e18303212593cd6': 'Data Architect',
 '1a281bf4bd1fe9b2a6e464e508bea167': 'Data Storage Specialist',
 '2f704538f6c9d6459a97314be98124e2': 'Data Collector',
 '3161063d378eecc4581c5cdee46a2a6c': 'Head of Information Systems and Data Processing',
 '781f5d3a80812531fdc81125a527a626': 'Data Warehouse Specialist',
 '38a15ceadcdd6d4db16a88fa1a72b083': 'Data Warehouse Analyst',
 'e55556364d2096578fd153e9800e826f': 'Database Consultant',
 'd24ffac92c24fb0e7bd1abc5fc3b6254': 'Data Manager',
 'ccd7528fb38f16077360c5b67c9700c4': 'Data Communications Analyst',
 'f6fbd9dea1fa8f899683ade8e7d87d60': 'Data Entry Associate',
 '0de6170ccbed08e62b2e5862d5846a43': 'Database Tester',
 '499f9d9b6722342608656559b15abd90': 'Clinical Data Associate',
 '8a7a3f1bce0958ae9f090683e5a925b7': 'Data Scientist',
 '7acaed29536648e45ea2b82d45047fcf': 'Medical Data Analyst',
 '02e4c028f64f176de2f54bbc2f5403ce': 'Marketing Database Analyst',
 '569da68cdcac43a3b4a0126ea9170570': 'Database Designer',
 'ced804d972b03cca6d523ec8925a7943': 'Oracle Database Administrator (Oracle DBA)',
 '41b2978a2c07c5f477e60f26372d6c85': 'Database Management System Specialist (DBMS Specialist)',
 'd9e964a222fdd9527319ad88adbfaa2e': 'SQL Database Administrator',
 'ac47656fd51c2cd8037057262c910dc4': 'Data Processing Manager',
 'e49986dae76619a3941d280ee14d38ae': 'Data Miner',
 'f842344417ed2fc226d9cc00f9562458': 'Log Data Technician',
 '096536ec43ce2a7de73031b271a1c132': 'Flight Data Technician',
 'a33662485eb4ad97096183db945308f4': 'Automatic Data Processing Planner (ADP Planner)',
 '4f75f97ac5b5f00f9420074d501f0803': 'Data Capture Specialist',
 'f36c6ada3a808453a0bf241c74a4e994': 'Reference Data Expert',
 '41ba88cfd476ee8d5e3d9f7cea62f051': 'Data Recovery Planner',
 '894ca61c22718617c7e2404f582153da': 'Data Processing Consultant',
 '34d80517fe3bc143f9fc850386b8ffd7': 'Clinical Data Coordinator',
 'e7b3e1c6a32c7247cd4857e4c3574165': 'Data Processing Systems Analyst',
 '36ac256201657eeaa67ee95aaae3cd54': 'Data Warehousing Specialist',
 'bc6dcc49557388a9f53d6e642e73d7a2': 'Business Database Analyst',
 '00bff17fca67555d8d86e8ead86dcd70': 'Database Analyst',
 'b42566382f2d3deeca56d3667004fc9e': 'Data Center Manager',
 '7932d4705d002b47789c11edfaed685e': 'Data Control Assistant',
 'aee597cd78f235c9db9d3ca987c7c846': 'Database Development Project Manager',
 '1c37a6e2bf157c0eff4665c57c52602d': 'SCADA Technician (Supervisory Control and Data Acquisition Technician)',
 '46b09f5f86f1ed46a8cb8e14d41418c7': 'Survey Data Technician',
 'a2a9fbe67b4aa2b551ba0f3adac90a99': 'Engineer, System Electronic Data Processing (Engineer, System EDP)',
 '77d124811ae6887bd4ff42b0e2b49116': 'Data Warehouse Architect',
 'f05d2014d4a9adaab50fa1e0ca6f6c8c': 'Naval Tactical Data System--Combat Information Center Watch Officer, Carrier Controlled Approach Controller',
 'ac2588d5d7676a49bdcd038e4a0a0ec5': 'Data Compiler',
 '2173ff3afd8d28192f7cf119af201940': 'Data Modeling Specialist',
 'f5bc91b67dc30ad204158092116c4ed2': 'Clinical Data Manager',
 '433df1b945d32f17d9e61cf60a9bd06e': 'Data Abstractor',
 '1295a187473fd2f53427769fc7a4c02e': 'Clinical Data Management Associate Director',
 '004431b0c1ce29ff6145307fa23f3f98': 'Data Reduction Technician',
 '8fd068c8d9be73abfa678856177b6c40': 'Data Operations Director',
 'c34f03aa0a9c6edbe8ec50f4fa3687a8': 'Data Center Operator',
 '7aecc34a90868aac810bf3693b11534e': 'Clinical Trials Data Coordinator',
 '086f0063610283d1c23c44bca4ef92c0': 'Database Administrator (DBA)',
 '16b49a63ac3fcb90356c30187110ed94': 'Data Processing Auxiliary Equipment Operator',
 '437e4414c78611a270a5cedb4b4c0eed': 'Data Collection Technician',
 '679fb7003e0aedc14891fcd15dd846c5': 'Database Specialist',
 '7a37ddb38441873334fd8ff07c17ad22': 'Data Acquisition Technician',
 '58eaf730050d2e23c7361fbb782e30a2': 'Data Processing Mechanic',
 'd0abc47e83e7d85921e113f85175547a': 'Data Sciences Director',
 '73d251075a710326ae436d9819246377': 'Databases Software Consultant',
 '5e2bfe1fb8451158ff488c673535980c': 'Data Entry Machine Operator',
 'ac9f868b5c3e7cb3f31bcead5dadeb71': 'Micro Computer Data Processor',
 'f670246beda8187fbe875401e7bc4ba6': 'Data Processing Services Sales Representative',
 '0044971fda4a261b6049a63817913e95': 'Data Processing Equipment Repairer',
 'b36bc5f02fd641a126df999bcefa2777': 'Data Technician',
 '067c85859a63aa6f1c8c936904124dd6': 'Naval Tactical Data System--Combat Information Center Officer',
 '491d82be40d8395e347f9584124bccdd': 'Flight Test Data Acquisition Technician',
 '7028f15ad274cb4d9505101b9c1306b1': 'Clinical Data Management Manager (CDM Manager)',
 'fd69391dc29c83d5ad744daa57de0175': 'Data Transcriber',
 '3def30a9bc4356164176ba909f40bab8': 'Data Input Clerk',
 '132aa9e82c5d4c8a395342d0a6e22c5c': 'Electronic Data Interchange System Developer (EDI System Developer)',
 '07b2ace822aff5d35dcf5ea264ef3b59': 'Database Administration Project Manager',
 'f8984e50675cf61e5ac1ea8f661e0ab2': 'Field Traffic Data Technician',
 'd329d187dafb7546061ec7fbf137a2b4': 'Clinical Data Abstractor',
 'd63e35f948115e0c328a49db7bdb6e59': 'Data Control Clerk Supervisor',
 'bf7f43295d45cdced048c8126f977b6b': 'Datastage Developer',
 '6bf4290b983d58ce153af610008846c9': 'Data Entry Technician',
 'f1fc61f279e3ad14863e582ca6fdc473': 'Clinical Data Analyst',
 '31bf3181813e21ffdfd76b5881fab066': 'Data Entry Supervisor',
 '04b0eaf624b2deb45ccd62cf6ec7c7bc': 'Data Conversion Operator',
 '2616d64becb4f2c478dd42f501bbfbff': 'Data Processing Control Clerk',
 '776bf47111206d31ccf835650e1054cc': 'Data Typist',
 'c3b5ebd7b88c20786f11e87846c7d6ae': 'SCADA Operator (Supervisory Control and Data Acquisition Operator)',
 'dfea9e8bc3c565ff9e64d4288b1c423d': 'Customer Data Technician',
 'a50d1f4be063829950e6ddb02c91379f': 'Database Programmer',
 'af6630abd24c19f77cfba94aa4e3b7e1': 'Data Specialist',
 '901740e84d1a4760e440b039adac9df2': 'Data Processing Clerk',
 'f2ecf36d7eb0a4225974fc6c4f48cfcb': 'Voice and Data Technician',
 'f1fb62e4c97f4f5cd5001877cb94379e': 'Data Processor',
 'b9a57264eaada670703db113483ddfc3': 'Data Modeler',
 '65b92572bca68ff9c49c930749fa348c': 'LiDAR Data Analyst',
 '59dab7d0a3ee97d939aa8b1a8deec857': 'Data Management Manager',
 'afea0e0169a98ee264db2ddb1c6e6a34': 'Data Processing Supervisor',
 '0facaffe51cc1998a5fbdbe5fd18fd98': 'Weight in Motion Field Data Collection Technician',
 'ccf2c4daae069f054cada4c911819a17': 'Scientific Database Curator',
 '1426c924e1b6b162f6bfdd1906d98d0e': 'Operations Officer, Afloat (Naval Tactical Data Systems)',
 'eb3d789747d52df803ce63fe37bf53e9': 'Data Analyst',
 'bdf4dcd92089bc17345de83f4d06090f': 'Data Entry Operator',
 '5285758deb04c98f58cbae2747195f33': 'Data Reviewer',
 '04c27c76b463a917800549cf88a59961': 'Data Communications Technician',
 '631bc3a12ed11340fc94ebfffa8f5f4e': 'Database Technician',
 'b0fa6ede410f50b82ab74f5a705fe699': 'Analytical Data Miner',
 '559a21f836c93876f31b60e6d10656a7': 'Data Analysis Assistant',
 'c1fb1a01b78373ac2153c66fa08d16dc': 'Data Examination Clerk',
 '05bb9a333a66d6eb151e253623efe1c0': 'Data Entry Clerk',
 '4cee16550636e292b8d136486fce943b': 'Data Capture Clerk'}

In [7]:
df_final_web['Job Title']= df_final_web['normalized_job_code']

for k,v in dict_uuid_title.items():
    df_final_web.loc[df_final_web['normalized_job_code']==k,'Job Title']=v

In [8]:
print(df_final_web.info(memory_usage='deep'))
df_final_web.nunique()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9649 entries, 0 to 9648
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   uuid                 9649 non-null   object
 1   age                  9649 non-null   int64
 2   gender               9649 non-null   category
 3   dem_has_children     9649 non-null   category
 4   age_group            9649 non-null   category
 5   country_code         9649 non-null   category
 6   rural                9649 non-null   category
 7   dem_education_level  8986 non-null   object
 8   dem_full_time_job    9649 non-null   category
 9   normalized_job_code  5702 non-null   object
 10  awareness            9649 non-null   category
 11  vote                 9649 non-null   category
 12  effect               9649 non-null   category
 13  argumentsfor         9649 non-null   object
 14  argumentsagainst     9649 non-null   object
 15  Country              9649 non-null   object
 16  Job Title            5702 non-null   object
dtypes: category(9), int64(1), object(7)
memory usage: 6.8 MB
None

uuid                   9649
age                      52
gender                    2
dem_has_children          2
age_group                 3
country_code             28
rural                     2
dem_education_level       4
dem_full_time_job         2
normalized_job_code     156
awareness                 4
vote                      5
effect                    9
argumentsfor            674
argumentsagainst        881
Country                  28
Job Title               156
dtype: int64

In [10]:
df_final_web.loc[df_final_web['Job Title'].isnull(),'dem_full_time_job'].value_counts()

no     3947
yes       0
Name: dem_full_time_job, dtype: int64

In [8]:
df_final_web.loc[df_final_web['Job Title'].isnull(),'Job Title']='Unemployed or Part time Job or Inactive'

In [14]:
df_final_web

,uuid,age,gender,dem_has_children,age_group,country_code,rural,dem_education_level,dem_full_time_job,normalized_job_code,awareness,vote,effect,argumentsfor,argumentsagainst,Country,Job Title
1,54f0f1c0-dda1-0133-a559-0a81e8b09a82,57,Male,yes,40_65,AT,urban,high,yes,861a9b9151e11362eb3c77ca914172d0,I understand it fully,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working,Austria,Automatic Data Processing Planner
3,15626d40-db13-0133-ea5c-0a81e8b09a82,45,Male,yes,40_65,AT,rural,high,yes,049a3f3a2b5f85cb2971ba77ad66e10c,I have heard just a little about it,I would probably vote for it,I work less,It reduces anxiety about financing basic needs,None of the above,Austria,Data Coordinator
4,24954a70-db98-0133-4a64-0a81e8b09a82,41,Female,yes,40_65,AT,urban,high,yes,f4b2fb1aa40f661488e2782b6d57ad2f,I have heard just a little about it,I would probably vote for it,None of the above,It reduces anxiety about financing basic needs,It is impossible to finance | It might encoura...,Austria,Database Developer
5,28583060-dbe2-0133-ff9c-0a81e8b09a82,26,Female,no,26_39,AT,rural,high,yes,27af8700f5577cec835acee2cb90a2ff,I understand it fully,I would vote against it,A basic income would not affect my work choices,It encourages financial independence and self-...,It is impossible to finance | It might encoura...,Austria,Data Entry Specialist
7,dd743bb0-d9a5-0133-53b2-0a81e8b09a82,47,Male,no,40_65,AT,urban,medium,yes,c1b670eba9ccb65e7c99f7da116d5b9c,I know something about it,I would probably vote for it,A basic income would not affect my work choices,It increases appreciation for household work a...,It might encourage people to stop working | Fo...,Austria,Database Architect
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9641,24262070-d8e2-0133-b561-0a81e8b09a82,16,Female,yes,14_25,SK,urban,None,yes,41b2978a2c07c5f477e60f26372d6c85,I have never heard of it,I would not vote,I spend more time with my family,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...,Slovakia,Database Management System Specialist (DBMS Sp...
9644,7d1ac020-dcb4-0133-817a-0a81e8b09a82,37,Female,no,26_39,SK,urban,high,yes,847165cfda6b1dc82ae22b967da8af2f,I understand it fully,I would probably vote for it,I spend more time with my family,It reduces bureaucracy and administrative expe...,It is impossible to finance,Slovakia,Data Warehouse Developer
9645,39f989f0-db52-0133-8482-0a81e8b09a82,53,Male,yes,40_65,SK,urban,high,yes,a4d5b8b38f9513825d0d94a981ebe962,I have never heard of it,I would probably vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | On...,Slovakia,Database Manager
9647,2896e440-db3c-0133-5b67-0a81e8b09a82,47,Male,yes,40_65,SK,urban,low,yes,775190277a849cba701b306a7b374c0a,I understand it fully,I would vote for it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,Foreigners might come to my country and take a...,Slovakia,Data Officer
9648,06217ba0-dd56-0133-edda-0a81e8b09a82,51,Female,yes,40_65,SK,urban,high,yes,8a7a3f1bce0958ae9f090683e5a925b7,I understand it fully,I would vote against it,A basic income would not affect my work choices,It reduces bureaucracy and administrative expe...,It might encourage people to stop working | It...,Slovakia,Data Scientist

In [13]:


df_final_web=df_final_web.loc[~df_final_web['Job Title'].isnull()]




print(df_final_web.info(memory_usage='deep'))
df_final_web.nunique()

                                      uuid  age  gender dem_has_children  \
1     54f0f1c0-dda1-0133-a559-0a81e8b09a82   57    Male              yes
3     15626d40-db13-0133-ea5c-0a81e8b09a82   45    Male              yes
4     24954a70-db98-0133-4a64-0a81e8b09a82   41  Female              yes
5     28583060-dbe2-0133-ff9c-0a81e8b09a82   26  Female               no
7     dd743bb0-d9a5-0133-53b2-0a81e8b09a82   47    Male               no
...                                    ...  ...     ...              ...
9641  24262070-d8e2-0133-b561-0a81e8b09a82   16  Female              yes
9644  7d1ac020-dcb4-0133-817a-0a81e8b09a82   37  Female               no
9645  39f989f0-db52-0133-8482-0a81e8b09a82   53    Male              yes
9647  2896e440-db3c-0133-5b67-0a81e8b09a82   47    Male              yes
9648  06217ba0-dd56-0133-edda-0a81e8b09a82   51  Female              yes

     age_group country_code  rural dem_education_level dem_full_time_job  \
1        40_65           AT  urban                high               yes
3        40_65           AT  rural                high               yes
4        40_65           AT  urban                high               yes
5        26_39           AT  rural                high               yes
7        40_65           AT  urban              medium               yes
...        ...          ...    ...                 ...               ...
9641     14_25           SK  urban                None               yes
9644     26_39           SK  urban                high               yes
9645     40_65           SK  urban                high               yes
9647     40_65           SK  urban                 low               yes
9648     40_65           SK  urban                high               yes

                   normalized_job_code                            awareness  \
1     861a9b9151e11362eb3c77ca914172d0                I understand it fully
3     049a3f3a2b5f85cb2971ba77ad66e10c  I have heard just a little about it
4     f4b2fb1aa40f661488e2782b6d57ad2f  I have heard just a little about it
5     27af8700f5577cec835acee2cb90a2ff                I understand it fully
7     c1b670eba9ccb65e7c99f7da116d5b9c            I know something about it
...                                ...                                  ...
9641  41b2978a2c07c5f477e60f26372d6c85             I have never heard of it
9644  847165cfda6b1dc82ae22b967da8af2f                I understand it fully
9645  a4d5b8b38f9513825d0d94a981ebe962             I have never heard of it
9647  775190277a849cba701b306a7b374c0a                I understand it fully
9648  8a7a3f1bce0958ae9f090683e5a925b7                I understand it fully

                                  vote  \
1         I would probably vote for it
3         I would probably vote for it
4         I would probably vote for it
5              I would vote against it
7         I would probably vote for it
...                                ...
9641                  I would not vote
9644      I would probably vote for it
9645  I would probably vote against it
9647               I would vote for it
9648           I would vote against it

                                               effect  \
1     A basic income would not affect my work choices
3                                         I work less
4                                   None of the above
5     A basic income would not affect my work choices
7     A basic income would not affect my work choices
...                                               ...
9641                 I spend more time with my family
9644                 I spend more time with my family
9645  A basic income would not affect my work choices
9647  A basic income would not affect my work choices
9648  A basic income would not affect my work choices

                                           argumentsfor  \
1     It increases appreciation for household work a...
3        It reduces anxiety about financing basic needs
4        It reduces anxiety about financing basic needs
5     It encourages financial independence and self-...
7     It increases appreciation for household work a...
...                                                 ...
9641  It reduces bureaucracy and administrative expe...
9644  It reduces bureaucracy and administrative expe...
9645  It reduces bureaucracy and administrative expe...
9647  It reduces bureaucracy and administrative expe...
9648  It reduces bureaucracy and administrative expe...

                                       argumentsagainst   Country  \
1             It might encourage people to stop working   Austria
3                                     None of the above   Austria
4     It is impossible to finance | It might encoura...   Austria
5     It is impossible to finance | It might encoura...   Austria
7     It might encourage people to stop working | Fo...   Austria
...                                                 ...       ...
9641  Foreigners might come to my country and take a...  Slovakia
9644                        It is impossible to finance  Slovakia
9645  It might encourage people to stop working | On...  Slovakia
9647  Foreigners might come to my country and take a...  Slovakia
9648  It might encourage people to stop working | It...  Slovakia

                                              Job Title
1                     Automatic Data Processing Planner
3                                      Data Coordinator
4                                    Database Developer
5                                 Data Entry Specialist
7                                    Database Architect
...                                                 ...
9641  Database Management System Specialist (DBMS Sp...
9644                           Data Warehouse Developer
9645                                   Database Manager
9647                                       Data Officer
9648                                     Data Scientist

[5702 rows x 17 columns]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 5702 entries, 1 to 9648
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   uuid                 5702 non-null   object
 1   age                  5702 non-null   int64
 2   gender               5702 non-null   category
 3   dem_has_children     5702 non-null   category
 4   age_group            5702 non-null   category
 5   country_code         5702 non-null   category
 6   rural                5702 non-null   category
 7   dem_education_level  5446 non-null   object
 8   dem_full_time_job    5702 non-null   category
 9   normalized_job_code  5702 non-null   object
 10  awareness            5702 non-null   category
 11  vote                 5702 non-null   category
 12  effect               5702 non-null   category
 13  argumentsfor         5702 non-null   object
 14  argumentsagainst     5702 non-null   object
 15  Country              5702 non-null   object
 16  Job Title            5702 non-null   object
dtypes: category(9), int64(1), object(7)
memory usage: 4.6 MB
None

uuid                   5702
age                      52
gender                    2
dem_has_children          2
age_group                 3
country_code             28
rural                     2
dem_education_level       4
dem_full_time_job         1
normalized_job_code     156
awareness                 4
vote                      5
effect                    9
argumentsfor            466
argumentsagainst        716
Country                  28
Job Title               156
dtype: int64

In [11]:
print(df_final_web.info(memory_usage='deep'))
df_final_web.nunique()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9649 entries, 0 to 9648
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   uuid                 9649 non-null   object
 1   age                  9649 non-null   int64
 2   gender               9649 non-null   category
 3   dem_has_children     9649 non-null   category
 4   age_group            9649 non-null   category
 5   country_code         9649 non-null   category
 6   rural                9649 non-null   category
 7   dem_education_level  8986 non-null   object
 8   dem_full_time_job    9649 non-null   category
 9   normalized_job_code  5702 non-null   object
 10  awareness            9649 non-null   category
 11  vote                 9649 non-null   category
 12  effect               9649 non-null   category
 13  argumentsfor         9649 non-null   object
 14  argumentsagainst     9649 non-null   object
 15  Country              9649 non-null   object
 16  Job Title            5702 non-null   object
dtypes: category(9), int64(1), object(7)
memory usage: 6.8 MB
None

uuid                   9649
age                      52
gender                    2
dem_has_children          2
age_group                 3
country_code             28
rural                     2
dem_education_level       4
dem_full_time_job         2
normalized_job_code     156
awareness                 4
vote                      5
effect                    9
argumentsfor            674
argumentsagainst        881
Country                  28
Job Title               156
dtype: int64

In [10]:
df_final_web['Job Title'].value_counts()

Unemployed or Part time Job or Inactive                              3947
Data Officer                                                          101
Automatic Data Processing Customer Liaison (ADP Customer Liaison)      88
Computer or Data Processing Systems Consultant                         88
Data Coordinator                                                       88
                                                                     ...
Data Processing Mechanic                                                6
Clinical Trials Data Coordinator                                        5
Data Reviewer                                                           5
Data Center Manager                                                     4
Database Technician                                                     4
Name: Job Title, Length: 157, dtype: int64

In [11]:
df_final_web.to_parquet('../data/processed/df_final_api.parquet')