In [54]:
from sklearn.preprocessing import RobustScaler, StandardScaler
from statsmodels.robust.scale import huber
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import plotly.express as px
import re
import locale
plt.style.use('seaborn')
%matplotlib inline

pd.set_option('display.max_rows', 0)
pd.set_option('display.max_columns', 0)


df_indicadores_pob = pd.read_parquet(f'../data/processed/df_indicadores_pob.parquet')
df_final_pob = pd.read_parquet('../data/processed/df_final_pob.parquet')
df_final_pob_melt = pd.read_parquet('../data/processed/df_final_pob_melt.parquet')
df_final_pob_melt_PC = pd.read_parquet('../data/processed/df_final_pob_melt_PC.parquet')

In [21]:
municipio_types='Abla'

cohorte = df_final_pob.loc[df_final_pob['Nombre Ente Principal'] == municipio_types , 'cohorte_pob'].unique().to_list()[0]


df=df_final_pob[['Nombre Ente Principal','cohorte_pob','PC_TOTAL']].loc[(df_final_pob['cohorte_pob'] == cohorte)&(df_final_pob['PC_TOTAL'] >1)].sort_values(by='PC_TOTAL' , ascending=False)
df['Nombre Ente Principal'] = df['Nombre Ente Principal'].astype('object')
df['PC_TOTAL'] = df.apply(lambda new: round(new['PC_TOTAL'],), axis=1)
df = [df.head(2) , df.loc[df['Nombre Ente Principal'] == municipio_types] , df.tail(2)]
df = pd.concat(df)
df.iloc[2 , 0] = f'{municipio_types}.'


df

     Nombre Ente Principal cohorte_pob  PC_TOTAL
3422                  Ascó   1000-2000      5324
3912               Cerdido   1000-2000      2599
0                    Abla.   1000-2000      1021
3577             Almendral   1000-2000        37
1870                Turcia   1000-2000        26

In [32]:
municipio_types='Abla'
partida_de_coste_types='PC_Abastecimiento de agua potable'

cohorte = df_final_pob_melt_PC.loc[df_final_pob_melt_PC['Nombre Ente Principal'] == municipio_types , 'cohorte_pob'].unique().to_list()[0]


df=df_final_pob_melt_PC[['Nombre Ente Principal','cohorte_pob','Descripción','coste_efectivo_PC']].loc[(df_final_pob_melt_PC['cohorte_pob'] == cohorte)&(df_final_pob_melt_PC['coste_efectivo_PC'] >=1)&(df_final_pob_melt_PC['Descripción'] ==partida_de_coste_types)].sort_values(by='coste_efectivo_PC' , ascending=False)
df['Nombre Ente Principal'] = df['Nombre Ente Principal'].astype('object')
df['coste_efectivo_PC'] = df.apply(lambda new: round(new['coste_efectivo_PC'],), axis=1)
df = [df.head(2) , df.loc[df['Nombre Ente Principal'] == municipio_types] , df.tail(2)]
df = pd.concat(df)
df.iloc[2 , 0] = f'{municipio_types}.'


df

     Nombre Ente Principal  ... coste_efectivo_PC
4838              Sinarcas  ...               369
4619                 Viver  ...               332
0                    Abla.  ...               229
3967            Vilarmaior  ...                 1
3935               Monfero  ...                 1

[5 rows x 4 columns]

In [24]:
df_final_pob_melt_PC

                        CCAA  ... coste_efectivo_PC
0                  Andalucía  ...        229.091814
1                  Andalucía  ...         67.154470
2                  Andalucía  ...         50.507831
3                  Andalucía  ...         80.781023
4                  Andalucía  ...        253.247150
5                  Andalucía  ...          0.000000
6                  Andalucía  ...         76.099570
7                  Andalucía  ...         94.710739
8                  Andalucía  ...        270.958444
...                      ...  ...               ...
209358  Comunitat Valenciana  ...          1.000506
209359  Comunitat Valenciana  ...          0.000000
209360  Comunitat Valenciana  ...         96.336416
209361  Comunitat Valenciana  ...         28.088929
209362  Comunitat Valenciana  ...         35.867246
209363  Comunitat Valenciana  ...         43.507288
209364  Comunitat Valenciana  ...          0.000000
209365  Comunitat Valenciana  ...         18.963799
209366  Comunitat Valenciana  ...         66.531704

[209367 rows x 8 columns]

In [24]:
import json


with open('/home/carpiero/ir/es-atlas/shapefiles_espana_municipios.geojson') as response:
    counties = json.load(response)
    
json= pd.read_csv('/home/carpiero/ir/es-atlas/shapefiles_espana_municipios.csv')

In [56]:
print(counties["features"][2]["properties"])

{'cartodb_id': 8133, 'nameunit': 'Santa Úrsula', 'natcode': '34053838039', 'f_codmun': 38039, 'codmun': '039', 'codccaa': '38', 'codmun_no_0': '39', 'codccaa_no_0': '38', 'f_codmun_no_0': 3839}

In [58]:
pd.set_option('display.max_columns', None)
df_final_pob[['CCAA', 'Provincia', 'Tipo Ente Principal', 'Nombre Ente Principal',
       'Código Ente Principal','codigoM','codigo_geo']].loc[df_final_pob['Nombre Ente Principal']=='Barcelona']

,CCAA,Provincia,Tipo Ente Principal,Nombre Ente Principal,Código Ente Principal,codigoM,codigo_geo
2825,Cataluña,Barcelona,Ayuntamiento,Barcelona,09-08-019-AA-000,08019,8019

In [60]:
ciudad='Oviedo'

In [61]:
df_final_pob[['CCAA', 'Provincia', 'Tipo Ente Principal', 'Nombre Ente Principal',
       'Código Ente Principal','codigoM','codigo_geo']].loc[df_final_pob['Nombre Ente Principal']==ciudad]

,CCAA,Provincia,Tipo Ente Principal,Nombre Ente Principal,Código Ente Principal,codigoM,codigo_geo
1155,Principado de Asturias,Asturias,Ayuntamiento,Oviedo,03-33-044-AA-000,33044,33044

In [53]:
json.loc[json['nameunit']==ciudad]

,the_geom,cartodb_id,nameunit,natcode,f_codmun,codmun,codccaa,codmun_no_0,codccaa_no_0,f_codmun_no_0
491,0106000020E6100000010000000103000000010000003A...,758,Oviedo,34033333044,33044,44,33,44,33,3344

In [16]:
# fig = px.choropleth_mapbox(df_final_pob, geojson=counties, locations='codigoM', color='PC_TOTAL',
#                            color_continuous_scale="Viridis",
# #                            range_color=(0, 12),
#                            mapbox_style="carto-positron",featureidkey="properties.f_codmun",
#                            zoom=4, center = {"lat": 40.463667, "lon": -3.74922},
#                            opacity=0.5,
#                            labels={'unemp':'unemployment rate'}
#                           )
# fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
# fig.show()

In [63]:
df_final_pob['PC_TOTAL'].describe()

count    4869.000000
mean      573.644779
std       458.223443
min         0.000000
25%       299.443169
50%       477.853185
75%       707.883274
max      5323.980060
Name: PC_TOTAL, dtype: float64